openapi/components/schemas/Token.yaml, openapi/openapi.yaml, openapi/paths/recurring@{your_customer_reference}@remove@{your_token}.yaml, openapi/paths/recurring@{your_customer_reference}@update@{your_token}.yaml
=> DOCS-2951: Document DELETE /recurring/{your_customer_reference}/remove/{your_token}

openapi/components/examples/requests/post-orders/fastcheckout.json, openapi/paths/orders.yaml
=> DOCS-2995: Add FCO example

openapi/components/examples/requests/post-orders/payment-component.json, openapi/paths/orders.yaml
=> DOCS-2994: Add Payment Component examples to POST /orders

openapi/openapi.yaml, openapi/paths/accounts.yaml, openapi/paths/accounts@{account_id}.yaml, openapi/paths/accounts@{account_id}@bank-accounts.yaml, openapi/paths/accounts@{account_id}@sites.yaml, openapi/paths/accounts@{account_id}@ubos.yaml, openapi/paths/bank-accounts@{bankaccount_id}@bank-statements.yaml, openapi/paths/capture@{order_id}.yaml, openapi/paths/categories.yaml, openapi/paths/me.yaml, openapi/paths/orders@{capture_order_id}.yaml, openapi/paths/orders@{order_id}@capture.yaml, openapi/paths/pad@ccs.yaml, openapi/paths/pad@orders@{order_id}.yaml, openapi/paths/recurring@{your_customer_reference}.yaml, openapi/paths/recurring@{your_customer_reference}@remove@{your_token}.yaml, openapi/paths/recurring@{your_customer_reference}@token@{your_token}.yaml, openapi/paths/recurring@{your_customer_reference}@update@{your_token}.yaml, openapi/paths/ubos@{ubo_id}@identitydocs.yaml
=> DOCS-3002: Adjust order of tags in side menu

openapi/components/examples/requests/post-orders/recurring-initial.json, openapi/components/examples/requests/post-orders/recurring-subsequent.json, openapi/components/schemas/CustomerObject.yaml, openapi/components/schemas/Order.yaml, openapi/openapi.yaml, openapi/paths/customers.yaml, openapi/paths/customers@{customer_id}@delivery-details.yaml, openapi/paths/customers@{customer_id}@payment-methods.yaml, openapi/paths/orders.yaml, openapi/paths/transactions@{transaction_id}.yaml
=> DOCS-3046: Add recurring payments examples to POST orders

openapi/components/examples/requests/post-orders/server-to-server.json, openapi/paths/orders.yaml
=> DOCS-3047: Add server to server example to POST orders

openapi/components/schemas/SubaccountCharge.yaml, openapi/components/schemas/SubaccountPayout.yaml, openapi/components/schemas/var12.yaml, openapi/components/schemas/var3.yaml, openapi/paths/accounts@{account_id}@charges.yaml, openapi/paths/accounts@{account_id}@payouts.yaml
=> DOCS-2996: add maxLength for var 1 / var 2 / var 3

docs/array-schema-template.md, docs/delete-template.md, docs/get-template.md, docs/object-schema-template.md, docs/patch-template.md, docs/post-template.md, docs/variable-schema-template.md
=> DOCS-2993: add templates for API operations

openapi/paths/recurring@{your_customer_reference}.yaml, openapi/paths/recurring@{your_customer_reference}@remove@{your_token}.yaml, openapi/paths/recurring@{your_customer_reference}@token@{your_token}.yaml, openapi/paths/recurring@{your_customer_reference}@update@{your_token}.yaml
=> DOCS-3056: Change Recurring payments tag to Tokens

openapi/components/errors/Error1006.yaml, openapi/components/requestBody/CancelOrder.yaml, openapi/components/requestBody/ShipOrder.yaml, openapi/components/schemas/Amount.yaml, openapi/components/schemas/Currency.yaml, openapi/components/schemas/Description.yaml, openapi/components/schemas/GenericErrorResponse.yaml, openapi/components/schemas/Items.yaml, openapi/paths/orders@{order_id}.yaml
=> DOCS-3004: Review /orders/order_id

openapi/paths/categories.yaml
=> DOCS-3021: review listWebsiteCategories

openapi/paths/payment-methods.yaml
=> DOCS-3035: Review Get payment method

openapi/paths/recurring@{your_customer_reference}@remove@{your_token}.yaml
=> DOCS-3039: Review Delete token

openapi/paths/recurring@{your_customer_reference}@update@{your_token}.yaml
=> DOCS-3040: Review Update card expiry date

openapi/components/schemas/Ubo.yaml, openapi/paths/accounts@{account_id}@ubos.yaml, openapi/paths/ubos@{ubo_id}.yaml
=> DOCS-3076: Remove fax property from UBO object

openapi/components/requestBody/UpdateAccount.yaml, openapi/components/schemas/Account.yaml, openapi/paths/accounts@{account_id}.yaml, openapi/paths/customers@{customer_id}.yaml
=> DOCS-3010: Review Get affiliated account and Update affiliated account

openapi/paths/accounts@{account_id}@balances.yaml
=> DOCS-3011: Review List account balances

.github/Workflows/openapi-update-check.yml
=> DOCS-3077: add github action to check for API spec changes

openapi/components/schemas/Order.yaml
=> DOCS-3070: Update max length of custom parameters

openapi/components/requestBody/AddBankAccount.yaml, openapi/paths/bank-accounts@{bankaccount_id}.yaml
=> DOCS-3017: Review Get bank account

openapi/components/requestBody/AddBankStatement.yaml, openapi/paths/bank-accounts@{bankaccount_id}@bank-statements.yaml
=> DOCS-3018: Review Add bank statement and List bank statements

openapi/paths/bank-accounts@{bankaccount_id}@payment-links.yaml
=> DOCS-3019: Review Validate bank account

.github/workflows/openapi-update-check.yml
=> DOCS-3077: correct github action steps

.github/workflows/openapi-update-check.yml
=> DOCS-3077: restructure github action

openapi/paths/bank-statements@{bankstatement_id}.yaml
=> DOCS-3020: Review Get bank statement

openapi/components/requestBody/AddIdentityDoc.yaml, openapi/paths/identitydocs@{identitydoc_id}.yaml
=> DOCS-3028: Review Get identity document

.github/workflows/openapi-update-check.yml
=> DOCS-3077: fix file not found error

.github/workflows/openapi-update-check.yml
=> DOCS-3077: correct github contexts

openapi/components/requestBody/PayOutAffiliate.yaml, openapi/components/schemas/Payout.yaml, openapi/paths/accounts@{account_id}@charges.yaml, openapi/paths/accounts@{account_id}@payouts.yaml
=> DOCS-3014: Review Pay out affiliate

openapi/components/requestBody/AddUbo.yaml, openapi/paths/accounts@{account_id}@ubos.yaml, openapi/paths/sites@{site_id}.yaml
=> DOCS-3016: Review Add UBOs and List UBOs

openapi/components/requestBody/UpdateAccount.yaml, openapi/components/schemas/Account.yaml, openapi/paths/signup-account.yaml
=> DOCS-3041: Review Create affiliated account

openapi/openapi.yaml, openapi/paths/capture@{order_id}.yaml
=> DOCS-3022: Review Cancel authorized payment

openapi/openapi.yaml, openapi/paths/orders@{order_id}@capture.yaml
=> DOCS-3006: Review Capture Payment

.github/workflows/openapi-update-check.yml
=> DOCS-3077: add artifact actions

.github/workflows/openapi-update-check.yml, openapi.json
=> DOCS-3077: prettify JSON files

.github/workflows/openapi-update-check.yml
=> DOCS-3077: run github action nightly

openapi/paths/orders@{order_id}@files.yaml
=> DOCS-3007: Review Challenge chargebacks

openapi/components/requestBody/AddUbo.yaml, openapi/components/requestBody/UpdateAccount.yaml, openapi/components/schemas/Account.yaml, openapi/components/schemas/Address1.yaml, openapi/components/schemas/Address2.yaml, openapi/components/schemas/Address3.yaml, openapi/components/schemas/Apartment.yaml, openapi/components/schemas/BirthCountry.yaml, openapi/components/schemas/Birthday.yaml, openapi/components/schemas/City.yaml, openapi/components/schemas/CoCNumber.yaml, openapi/components/schemas/CompanyName.yaml, openapi/components/schemas/Country.yaml, openapi/components/schemas/DeliveryDetails.yaml, openapi/components/schemas/Email.yaml, openapi/components/schemas/Fax.yaml, openapi/components/schemas/MobilePhone.yaml, openapi/components/schemas/Order.yaml, openapi/components/schemas/Street.yaml, openapi/components/schemas/Title.yaml, openapi/components/schemas/Ubo.yaml, openapi/components/schemas/VAT.yaml, openapi/components/schemas/ZIP.yaml, openapi/paths/pad@ccs.yaml
=> DOCS-3033: Review Request CCS

openapi.json
=> DOCS-0000: update openapi.json

openapi/paths/gateways.yaml
=> DOCS-3049: Check query parameters for GET gateways

openapi/components/errors/410Error.yaml, openapi/components/errors/Error1006.yaml, openapi/components/errors/Error1023.yaml, openapi/components/errors/Error1032.yaml, openapi/components/requestBody/CancelOrder.yaml, openapi/components/requestBody/ChargeAffiliate.yaml, openapi/components/requestBody/PayOutAffiliate.yaml, openapi/components/requestBody/Refund.yaml, openapi/components/requestBody/ShipOrder.yaml, openapi/components/schemas/Charge.yaml, openapi/components/schemas/CustomerObject.yaml, openapi/components/schemas/Item.yaml, openapi/components/schemas/ItemRefund.yaml, openapi/components/schemas/Order.yaml, openapi/components/schemas/Payout.yaml, openapi/components/schemas/Transaction.yaml, openapi/openapi.yaml, openapi/paths/bank-accounts@{bankaccount_id}@payment-links.yaml, openapi/paths/orders@{order_id}.yaml, openapi/paths/orders@{order_id}@files.yaml, openapi/paths/recurring@{your_customer_reference}@remove@{your_token}.yaml, openapi/paths/recurring@{your_customer_reference}@token@{your_token}.yaml, openapi/paths/recurring@{your_customer_reference}@update@{your_token}.yaml, openapi/paths/transactions.yaml, openapi/paths/transactions@{transaction_id}.yaml
=> DOCS-3085: lint OpenAPI reference

docs/delete-template.md, docs/get-template.md, docs/object-schema-template.md, docs/patch-template.md, docs/post-template.md, docs/variable-schema-template.md, openapi/paths/pad@orders@{order_id}.yaml
=> DOCS-3034: Review Get PAD order

openapi/components/examples/responses/listAffiliatedAccounts.json, openapi/components/schemas/Account.yaml, openapi/components/schemas/Address2.yaml, openapi/paths/accounts.yaml
=> DOCS-3093: Fix List affiliated accounts

openapi/components/schemas/PaymentMethod.yaml, openapi/paths/payment-methods.yaml
=> DOCS-3081: Review GET /payment-methods
